### ISSUE TITLE
Release Version: 2.0.5

### ISSUE THREAD

**Issue by Samigh** [webjars/tablesorter#8]
Hi 
@jamesward please can you release this version : 2.0.5

Thanks!

**Comment by jamesward** [comment]
I'm not seeing that release at: https://github.com/Mottie/tablesorter/releases

**Comment by Samigh** [comment]
unfortunately I need the old version 
 that's why I created another one https://github.com/Samigh/tablesorter
@jamesward  please can you fork this project

**Comment by jamesward** [comment]
Ah.  It looks like this should be a different artifact so you were right all along.  Here is the fork:
https://github.com/webjars/christianbach-tablesorter
